si: false
safe: true
source: https://loaimohamed.github.io/TestDSTL/Index.html
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
